//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHang.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;
    public partial class AdminUser
    {
        [Required(ErrorMessage = " Vui long nhap ma...")]
        [Display(Name ="Mã User")]
        public int ID { get; set; }
        [Required(ErrorMessage =" Vui long nhap ten...")]
        [Display(Name ="User Name")]
        public string NameUser { get; set; }
        [Display(Name ="Vi Tri")]
        public string RoleUser { get; set; }
        [Display(Name ="Nhap mat khau")]
        [Required(ErrorMessage =" Vui long nhap mat khau...")]
        [DataType(DataType.Password)]
        public string PasswordUser { get; set; }

       
        [NotMapped]
        [Compare("PasswordUser")]
        [Required(ErrorMessage =" Mat khau khong trung khop...")]
        [Display(Name ="Nhap lai mat khau")]
        public string ConfirmPass { get; set; }
        [NotMapped]
        public string ErrorLogin { get; set; }
    }
}
